import type { BobEditorPlugin } from '../../types.js';

export const mermaidPlugin: BobEditorPlugin = {
  name: 'mermaid',
  version: '1.0.0',
  sanitizeSchema: {
    tagNames: [
      'svg',
      'g',
      'path',
      'text',
      'tspan',
      'rect',
      'circle',
      'ellipse',
      'polygon',
      'polyline',
      'line',
      'marker',
      'defs',
      'title',
      'desc',
      'use',
      'symbol',
      'clipPath',
      'mask',
      'linearGradient',
      'radialGradient',
      'stop',
    ],
    attributes: {
      svg: [
        'xmlns',
        'width',
        'height',
        'viewBox',
        'preserveAspectRatio',
        'aria-label',
        'role',
        'id',
        'class',
      ],
      g: ['transform', 'fill', 'stroke', 'class', 'id'],
      path: ['d', 'fill', 'stroke', 'stroke-width', 'class', 'id', 'marker-end', 'marker-start'],
      text: [
        'x',
        'y',
        'dx',
        'dy',
        'text-anchor',
        'dominant-baseline',
        'fill',
        'class',
        'id',
        'transform',
      ],
      tspan: ['x', 'y', 'dx', 'dy'],
      rect: [
        'x',
        'y',
        'width',
        'height',
        'rx',
        'ry',
        'fill',
        'stroke',
        'stroke-width',
        'class',
        'id',
      ],
      circle: ['cx', 'cy', 'r', 'fill', 'stroke', 'stroke-width', 'class'],
      ellipse: ['cx', 'cy', 'rx', 'ry', 'fill', 'stroke', 'class'],
      polygon: ['points', 'fill', 'stroke', 'class'],
      polyline: ['points', 'fill', 'stroke', 'class'],
      line: ['x1', 'y1', 'x2', 'y2', 'stroke', 'stroke-width', 'class', 'marker-end'],
      marker: ['id', 'markerWidth', 'markerHeight', 'refX', 'refY', 'orient', 'markerUnits'],
      defs: [],
      use: ['href', 'x', 'y', 'width', 'height', 'class'],
      stop: ['offset', 'stop-color', 'stop-opacity'],
      linearGradient: ['id', 'x1', 'y1', 'x2', 'y2', 'gradientUnits'],
      radialGradient: ['id', 'cx', 'cy', 'r', 'fx', 'fy', 'gradientUnits'],
    },
  },
};
