import { defaultSchema } from 'rehype-sanitize';
import type { Options as Schema } from 'rehype-sanitize';
import { mergeSanitizeSchema } from './merge.js';

const CORE_EXTENSION: Schema = {
  tagNames: [
    // KaTeX math elements
    'math',
    'semantics',
    'annotation',
    'mrow',
    'msup',
    'msub',
    'msubsup',
    'mfrac',
    'mn',
    'mi',
    'mo',
    'mtext',
    'mspace',
    'mover',
    'munder',
    'munderover',
    'mtable',
    'mtr',
    'mtd',
    'msqrt',
    'mroot',
    'mfenced',
    'mpadded',
    'menclose',
    'mstyle',
    'merror',
    'mphantom',
    'mglyph',
    'mlabeledtr',
    'maligngroup',
    'malignmark',
    // Mermaid SVG
    'svg',
    'g',
    'path',
    'text',
    'tspan',
    'rect',
    'circle',
    'ellipse',
    'polygon',
    'polyline',
    'line',
    'marker',
    'defs',
    'title',
    'desc',
    'use',
    'symbol',
    'clipPath',
    'mask',
    'pattern',
    'image',
    'foreignObject',
    'linearGradient',
    'radialGradient',
    'stop',
    // Alerts/callouts
    'div',
    'section',
    'article',
    'aside',
    'header',
    'footer',
    'main',
    'figure',
    'figcaption',
    'mark',
    'kbd',
    'samp',
    'var',
    'sub',
    'sup',
  ],
  attributes: {
    // KaTeX: allow class on span elements for KaTeX rendering
    span: ['className', 'style', 'aria-hidden'],
    // Math elements
    math: ['xmlns', 'display'],
    annotation: ['encoding'],
    mspace: ['width', 'height', 'depth'],
    // SVG elements for mermaid
    svg: [
      'xmlns',
      'width',
      'height',
      'viewBox',
      'preserveAspectRatio',
      'aria-label',
      'role',
      'id',
      'class',
    ],
    g: ['transform', 'fill', 'stroke', 'class', 'id'],
    path: ['d', 'fill', 'stroke', 'stroke-width', 'class', 'id', 'marker-end', 'marker-start'],
    text: [
      'x',
      'y',
      'dx',
      'dy',
      'text-anchor',
      'dominant-baseline',
      'fill',
      'class',
      'id',
      'transform',
    ],
    tspan: ['x', 'y', 'dx', 'dy'],
    rect: [
      'x',
      'y',
      'width',
      'height',
      'rx',
      'ry',
      'fill',
      'stroke',
      'stroke-width',
      'class',
      'id',
    ],
    circle: ['cx', 'cy', 'r', 'fill', 'stroke', 'stroke-width', 'class'],
    ellipse: ['cx', 'cy', 'rx', 'ry', 'fill', 'stroke', 'class'],
    polygon: ['points', 'fill', 'stroke', 'class'],
    polyline: ['points', 'fill', 'stroke', 'class'],
    line: ['x1', 'y1', 'x2', 'y2', 'stroke', 'stroke-width', 'class', 'marker-end'],
    marker: ['id', 'markerWidth', 'markerHeight', 'refX', 'refY', 'orient', 'markerUnits'],
    defs: [],
    use: ['href', 'x', 'y', 'width', 'height', 'class'],
    // Alerts/callouts: allow data-* and className on div
    div: ['className', 'data-callout-type', 'data-type', 'role', 'aria-label'],
    // Heading slugs: allow id
    h1: ['id'],
    h2: ['id'],
    h3: ['id'],
    h4: ['id'],
    h5: ['id'],
    h6: ['id'],
    // Code blocks
    pre: ['className'],
    code: ['className'],
  },
};

export function getCoreSchema(): Schema {
  const base = structuredClone(defaultSchema) as Schema;
  return mergeSanitizeSchema(base, CORE_EXTENSION);
}
